import Head from 'next/head'

const AboutWorker = () => {
    return(
        <>
        <Head>
            <title>Dla Pracownikow</title>
            <meta name="description" content="Generated by Kamil Basak" />
        </Head>
        <div>
            
            <h3>Dla Pracownikow</h3>
            <p>
            <h4>Jesteśmy zadowoleni, że zainteresowałeś się Naszą firmą!</h4>

                Wśród naszych ofert każdy znajdzie dla siebie odpowiednią pracę. Bez względu na to, czy masz doświadczenie, czy nie, mamy dla Ciebie    propozycję. Z nami możesz zdobyć praktykę i umiejętności zawodowe, których wcześniej nie posiadałaś/eś. U nas znajdą zatrudnienie zarówno kandydaci z dobrą lub podstawową znajomością języka, jak i bez kompetencji językowych. Każdego kandydata przygotowujemy do wyjazdu i pracy u naszych klientów, prowadzimy szkolenia wstępne oraz wdrożenie językowe, pozwalające na szybką adaptację zawodową.

            </p>
            
        </div>
        </>
    )
}

export default AboutWorker