import Head from 'next/head'
import Formularz from '../components/Form'
import Image from 'next/image'
import Map from '../components/Mapa'

const contact = () => {
    return ( 
    <>
    <Head>
            <title>Kontakt</title>
            <meta name="description" content="Generated by Kamil Basak" />

    </Head>
    <div className="ContactPage">
        <div className="container"> 
            <div className="row">
            <div className="col">
                    <h3>Napisz do nas...</h3>  
                    <div className="contact-image">
                        <Image src="/men.png" width={123} height={128} alt="Men"/>
                    </div> 
                    <Formularz/>   
            </div>  
            <div className="col">
                <h2>Kontakt</h2>
                <p>
                Tel: +48 690 690 693<br/>
                Ul. Jarzębinowa 3/3<br/>
                05-100 Nowy Dwór Mazowiecki<br/>
                NIP: 5311711763 <br/>
                </p>  
                <Map/>
            </div>   
            </div>    
        </div> 
    </div>
    </>
    );
}

export default contact;