import Head from 'next/head'

const foremployer = () => {
    return ( 
        <>
        <Head>
            <title>Dla Pracodawcy</title>
            <meta name="description" content="Generated by Kamil Basak" />
        </Head>
        <div>
            <h3>Dla Pracodawcy</h3>
            <p>Wiec </p>
        </div> 
        </>
        );
}
export default foremployer;