import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Fullbody from '../components/Fullbody'
import Trust from '../components/Trust'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Strona Główna</title>
        <meta name="description" content="Generated by Kamil Basak" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper@7/swiper-bundle.min.css"
        />
      </Head>
      <Fullbody/>
      <Trust/>
    </div>
  )
}
